"""add phone number

Revision ID: 213d152b5128
Revises: b54ea1ad0668
Create Date: 2023-04-20 12:32:40.971819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d152b5128'
down_revision = 'b54ea1ad0668'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
